name: Run Python Tests for TAU3

on:
  push:
    paths:
      - 'TAU3/**'
  pull_request:
    paths:
      - 'TAU3/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r TAU3/requirements.txt

      - name: Run tests
        run: |
          pytest TAU3