name: Run Python Tests for TAU3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python 3.x
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      # Install dependencies from the requirements.txt file in TAU3
      - name: Install dependencies
        run: |
          cd TAU3
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the tests in the TAU3 folder
      - name: Run tests
        run: |
          cd TAU3
          python -m unittest discover
